name: Reload Website on Push

on:
  push:
    branches:
      - main # Trigger only on pushes to the main branch

jobs:
  reload:
    runs-on: ubuntu-latest
    steps:
      - name: Send GET request to reload website
        run: |
          curl -X GET http://3.107.203.197/reload-website
